name: Develop CI Pipeline

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  archtype:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-scrapper .

      - name: Create datalake
        run: mkdir datalake

      - name: Run Docker Container
        run:  docker run -d --name github-scrapper -e "BUCKET_NAME=neo4j-tscd-100-10-2024" -e "REGION=us-east-1" ${{ secrets.DOCKER_USERNAME }}/github-scrapper

      - name: View Docker Logs
        run: docker logs github-scrapper

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-scrapper:latest
